AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-auth

Transform:
- AWS::Serverless-2016-10-31

Resources:
  OrdersTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "orderId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "orderId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
  CreateOrderFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: src/
      Handler: createOrder.handler
      Runtime: nodejs14.x
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: !GetAtt OrdersTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref OrdersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /orders
            Method: POST

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
