AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-auth

Transform:
- AWS::Serverless-2016-10-31

Resources:

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
